---
name: aoc2021
version: 0.0.0.0
synopsis: Tools for managing bigquery datasets.
description: Please see README.org
homepage: https://github.com/korayal/AOC2021
maintainer: admin@koray.al
extra-source-files:
  - README.org

ghc-options: -fwarn-redundant-constraints -Wincomplete-record-updates

default-extensions:
  - DeriveDataTypeable
  - DeriveGeneric
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - NamedFieldPuns
  - TupleSections
  - TypeFamilies
  - CPP
  - TypeOperators
  - DataKinds
  - ScopedTypeVariables
  - BangPatterns
  - FunctionalDependencies
  - PolyKinds
  - TypeInType
  - InstanceSigs
  - DeriveFunctor
  - LambdaCase
  - MultiWayIf
  - DerivingStrategies

dependencies:
  - base
  - relude
  - text
  - lens
  - unordered-containers
  - conduit
  - bytestring
  - mono-traversable
  - containers
  - directory
  - time
  - random
  - binary
  - memory
  - base16-bytestring
  - base64-bytestring

library:
  source-dirs: src
